name: Test wip branches

on:
  push:
    # Run on every branches which will be merged on dev
    branches-ignore:
      - master
      - main
      - release
      - develop
    tags-ignore:
      - "**"

env:
  PYTHONPATH: "mse_home"

jobs:
  check:
    runs-on: [self-hosted, sgx]
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install .

      - name: Code format with black
        run: |
          black --check $PYTHONPATH

      - name: Import check with isort
        run: |
          isort --check $PYTHONPATH

      - name: Lint check with pylint
        run: |
          pylint --rcfile=setup.cfg $PYTHONPATH

      - name: Type check with mypy
        run: |
          mypy $PYTHONPATH

      - name: Lint check with pycodestyle
        run: |
          pycodestyle $PYTHONPATH

      - name: Lint check with pydocstyle
        run: |
          pydocstyle $PYTHONPATH

      - name: Run unit tests
        env:
          TEST_SIGNER_KEY: /opt/cosmian-internal/cosmian-signer-key.pem
          TEST_PCCS_URL: https://pccs.staging.mse.cosmian.com
        run: |
          pytest
