FROM ghcr.io/cosmian/mse-base-beta:738e2b82a166e9c602148e4c70b0994cb4a730c1     


RUN . /opt/venv/bin/activate && \
    pip3 install "flask==2.2.2" \
    "Flask-Cors==3.0.10" \
    "Flask-SQLAlchemy==3.0.2"
