FROM ghcr.io/cosmian/mse-base-beta:c3835c99403a554bdd4d39c5c88fcd03e3b56f6a


RUN . /opt/venv/bin/activate && \
    pip3 install "flask==2.2.2" \
    "Flask-Cors==3.0.10" \
    "Flask-SQLAlchemy==3.0.2"
